### ISSUE TITLE
jetson-inference package not found

### ISSUE THREAD

**Issue by niekdek** [tue-robotics/image_recognition#100]
Hi,

I'm trying to compile the image_recognition_jetson package. After cloning and compiling the jetson-inference package as done in `install_jetson_inference.bash`, Cmake can't (fully) find the package.

So when I build the image_recognition_jetson package I get the following warnings:
```
CMake Warning at image_recognition/image_recognition_jetson/CMakeLists.txt:25 (find_package):
  Found package configuration file:

    /usr/local/share/jetson-inference/cmake/jetson-inferenceConfig.cmake

  but it set jetson-inference_FOUND to FALSE so package "jetson-inference" is
  considered to be NOT FOUND.  Reason given by package:

  The following imported targets are referenced, but are missing:
  jetson-utils



CMake Warning at image_recognition/image_recognition_jetson/CMakeLists.txt:35 (message):
  Jetson-inference not found, using a mock instead ...


CMake Warning at image_recognition/image_recognition_jetson/CMakeLists.txt:36 (message):
  The library can be installed using scripts/install_jetson_inference.bash

```

Has anyone experienced anything similar before? Any help would be appreciated.

System info:
Jetson tx2
Ubuntu 16.04
ros kinetic

**Comment by reinzor** [comment]
Might be out of date, see https://github.com/dusty-nv/jetson-inference for more installation instructions.

**Comment by niekdek** [comment]
> Might be out of date, see https://github.com/dusty-nv/jetson-inference for more installation instructions.

Thanks for the response.
I flashed a clean installation of Ubuntu 16.04 to the Jetson and followed the installation instructions as suggested. The exact same issue still occurs.

Used `jetson-inference` installation procedure:
```
$ sudo apt-get update 
$ sudo apt-get install git cmake
$ git clone https://github.com/dusty-nv/jetson-inference
$ cd jetson-inference
$ git submodule update --init
$ sudo apt-get install libpython3-dev python3-numpy
$ mkdir build
$ cd build
$ cmake ../
$ make
$ sudo make install
$ sudo ldconfig
```

Building the `image_recognition_jetson` package succeeds, but the warnings from my initial post are thrown and the package uses the `jetson-inference` mock.

Do you have any suggestion?

**Comment by reinzor** [comment]
Apparently `jetson-inference` is not installed properly then since the `find_package` cmake call cannot find it. I don't have a set-up to debug this right now.

**Comment by rokusottervanger** [comment]
We worked out the installation problem: https://github.com/dusty-nv/jetson-inference/issues/417 I'll send a PR.
 
FYI: After fixing that, we ran into API changes. The workaround, for now, is to check out an older version of jetson-inference (June 2018) and work with that. You may want to consider migrating to the new API if you ever need to reinstall your Jetson :)
