### ISSUE TITLE
Something went wrong during retraining, ''module' object has no attribute 'scalar_summary''

### ISSUE THREAD

**Issue by DaxiongAI** [tue-robotics/image_recognition#11]
Something went wrong during retraining, ''module' object has no attribute 'scalar_summary''

**Comment by Rayman** [comment]
We didn't update our implementation to the newest tensorflow, we'll do that shortly. In the meantime, can you try out an earlier version?
```
pip install tensorflow==0.12
```

**Comment by xu199367** [comment]
ok

**Comment by xythobuz** [comment]
Can confirm, installing like this proved successful (using 0.12 results in many warnings about deprecated functions used):

    export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.11.0-cp27-none-linux_x86_64.whl
    sudo pip install --upgrade $TF_BINARY_URL
