### ISSUE TITLE
Conflict with openface_ros package from interaction_lab..

### ISSUE THREAD

**Issue by maxinho** [tue-robotics/image_recognition#12]
Thank you for your good work.

Is it correct that the ros package: openface_ros from interaction_lab is based on a completely different openface library (https://github.com/interaction-lab/openface_ros)?

As far as I understand it, there exists one openface library from the cambridge university and the one your package is based on from the cmu university. Is that right?

The package one can download using: sudo apt-get install ros-kinetic-image-recognition is based on your package right?

Best,
Max

**Comment by reinzor** [comment]
You are correct, our library is based on https://cmusatyalab.github.io/openface/ as mentioned in the README.md.

The package in the ROS Kinetic release is indeed our package: https://github.com/tue-robotics/image_recognition-release
