### ISSUE TITLE
It doesn't run unless you remove the .py from the command (so the tutorial has to be updated)

### ISSUE THREAD

**Issue by JosjaG** [tue-robotics/image_recognition#25]
rosrun tensorflow_ros object_recognition_node**.py** _graph_path:=/home/amigo/MEGA/data/robotics_testlabs/training_data_Josja/models_15/output_graph.pb _labels_path:=/home/amigo/MEGA/data/robotics_testlabs/training_data_Josja/models_15/output_labels.txt

**Comment by MatthijsBurgh** [comment]
fixed by #26
