### ISSUE TITLE
Object recognition node error

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/image_recognition#34]
Message: Error processing request: ('Failed to run tensorflow session: %s', ValueError("Cannot feed value of shape () for Tensor u'Cast:0', which has shape '(?, ?, 3)'",))
['Traceback (most recent call last):\n', '  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 625, in _handle_request\n    response = convert_return_to_response(self.handler(request), self.response_class)\n', '  File "/home/amigo/ros/kinetic/system/src/tensorflow_ros/scripts/object_recognition_node", line 61, in _recognize_srv_callback\n    sorted_result = self._recognizer.classify(self._bgr_image)\n', '  File "/home/amigo/ros/kinetic/system/src/tensorflow_ros/src/tensorflow_ros/object_recognizer.py", line 59, in classify\n    raise Exception("Failed to run tensorflow session: %s", e)\n', 'Exception: (\'Failed to run tensorflow session: %s\', ValueError("Cannot feed value of shape () for Tensor u\'Cast:0\', which has shape \'(?, ?, 3)\'",))\n']

**Comment by LoyVanBeek** [comment]
Which image did you feed into it? I say this error happening yesterday and that was because the image was an empty file. 

Nonetheless, the error should be handled more gracefully, but I think the problem is with the data you feed it.

**Comment by MatthijsBurgh** [comment]
I don't know. It was used on the robot. I have had this error multiple times today. But maybe it is related to an error, segmentation fault, :) in ed_perception, which I am trying to find/fix right now.

**Comment by LoyVanBeek** [comment]
I hope to add a check and better error message tonight
