### ISSUE TITLE
Image path not set, when wanting to save images

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/image_recognition#45]
[ERROR] [1513100614.242175]: ~save_images_folder is not defined but we would like to save images ...
Traceback (most recent call last):
  File "/home/amigo/ros/kinetic/system/src/openface_ros/scripts/face_recognition_node", line 204, in <module>
    service_publish_result_image)
  File "/home/amigo/ros/kinetic/system/src/openface_ros/scripts/face_recognition_node", line 50, in __init__
    rospy.signal_shutdown()
TypeError: signal_shutdown() takes exactly 1 argument (0 given)

**Comment by reinzor** [comment]
I think this error message is correct. What is the issue?

**Comment by LoyVanBeek** [comment]
There are 2 errors here:
- ```~save_images_folder is not defined but we would like to save images``` This is part of the launch file that is configured to save images but then the location is not specified
- When yielding that error, ```TypeError: signal_shutdown() takes exactly 1 argument (0 given)``` occurs because apparently that misses an argument (I guess signal_shutdown(-1) or something)

**Comment by MatthijsBurgh** [comment]
The problem is not only in the launch file, but also in https://github.com/tue-robotics/image_recognition/blob/master/openface_ros/scripts/face_recognition_node#L196. Which doesn't check the service and topic variable to save images.

**Comment by reinzor** [comment]
Let's discuss next tuesday; this is a configuration fault imo, not in the implementation

**Comment by MatthijsBurgh** [comment]
Let me describe an error case. save_images is false, because this is equal to ROBOT_REAL, so false is sim. Then the path is not retrieved from the param server. While topic_save_images or service_save_images could be true. This way the error is currently created.

Because save_images is also not passed to the OpenFaceRos, I think you should remove the parameter and don't use it to determine to retrieve the path or not. OR use it to overrule the topic/service parameter. But I don't think that is the correct use.

**Comment by reinzor** [comment]
Again, lets discuss Tuesday ...

**Comment by MatthijsBurgh** [comment]
I would say, https://github.com/tue-robotics/image_recognition/blob/master/openface_ros/scripts/face_recognition_node#L196 is still incorrect.
