### ISSUE TITLE
Retrain failed

### ISSUE THREAD

**Issue by melikavhf** [tue-robotics/image_recognition#58]
Hi . First at all apologize for my bad language

when I try to train my image folder an error occurs 

**Something went wrong during retraining, 'Unknown command line flag 's''** 

would you please help me .
 I guess , maybe I have mistake in  annotation part 
![1](https://user-images.githubusercontent.com/24391257/40622000-efa69f94-628e-11e8-9542-16fc01949191.png)

It's annotated folder that , image_recognition_rqt make for me . is it true or no? if no what can I do for correct it?
![an](https://user-images.githubusercontent.com/24391257/40622020-06c3475e-628f-11e8-8225-217943a19b58.png)

**Comment by MatthijsBurgh** [comment]
No, this is problem when using the train_gui with a newer version of tensorflow. The 's' argument is a argument for rqt, but is passed on to tensorflow, which returns an error.

So if you use tensorflow 1.4.1, the gui should work. For newer version of tensorflow, you should use `rosrun tensorflow_ros retrain` with the correct parameters. Check the retrain script for all possible parameters.

**Comment by melikavhf** [comment]
thanks for your attention and help. 
my problem has been solved .
