### ISSUE TITLE
tensorflow_ros: object_recognizer.py expects the images to be RGB but receives BGR images

### ISSUE THREAD

**Issue by JannisBush** [tue-robotics/image_recognition#63]
Hey, 
Thanks for this nice library.

I was playing around with the tensorflow_ros package and was confused that my red ball was recognized as a blue ball and vice versa. 
Looked into the issue and found out that **evaluate_classifier**, **get_object_recognition** and **object_recognition_node** all send BGR images to **object_recognizer.py**, but that script expects the images to be in RGB format. 
The easiest solution is to transform the images to RGB in **object_recognizer.py** before they get send to tensorflow. 

Best regards,
Jannis

**Comment by MatthijsBurgh** [comment]
fixed by #64
