### ISSUE TITLE
Support new tensorflow version

### ISSUE THREAD

**Issue by reinzor** [tue-robotics/image_recognition#69]
1.11 is not working, they transitions to the tensorflow hub

**Comment by MatthijsBurgh** [comment]
Update script with: https://github.com/tensorflow/hub/blob/master/examples/image_retraining/retrain.py

**Comment by reinzor** [comment]
Not necessarily , we should evaluate whether we would like to depend on the hub https://github.com/tensorflow/hub/blob/master/examples/image_retraining/retrain.py#L133

**Comment by MatthijsBurgh** [comment]
Fixed by #79. It is not needed to use Tensorflow Hub at the moment. Old implementation can still be used.
