### ISSUE TITLE
Update tensorflow pip dependency

### ISSUE THREAD

**Issue by reinzor** [tue-robotics/image_recognition#71]
Should be `python-tensorflow-pip` https://github.com/ros/rosdistro/pull/13724/files

**Comment by MatthijsBurgh** [comment]
Already in `tue-env` https://github.com/tue-robotics/tue-env/tree/master/installer/targets/ros-python-tensorflow-pip

**Comment by MatthijsBurgh** [comment]
And also correct in `image_recognition_tensorflow` https://github.com/tue-robotics/image_recognition/blob/master/image_recognition_tensorflow/package.xml and `image_recognition_keras` https://github.com/tue-robotics/image_recognition/blob/master/image_recognition_keras/package.xml

**Comment by MatthijsBurgh** [comment]
So not clear what the issue is.

**Comment by reinzor** [comment]
This has nothing to do with `tue-env`. This package tries to follow the default ros dependency installation using `rosdep`. Therefore, a rule should exist for all packages that are not within your workspace. See http://wiki.ros.org/rosdep

For some reason the ROS build is failing: http://build.ros.org/job/Kdev__image_recognition__ubuntu_xenial_amd64/37/console

Due to missing key `tensorflow`

**Comment by reinzor** [comment]
Falso positives, seems to be resolved by rosdep
