### ISSUE TITLE
People merging

### ISSUE THREAD

**Issue by LoyVanBeek** [tue-robotics/image_recognition#87]
For several RoboCup challenges, we have to deal with people and their properties.
In order to do this, the idea is to associate faces (from OpenFace) and skeletons (from OpenPose). The association can be done by assigning the skeleton who's 'nose' joint is in the bounding box of a face;s bounding box. 

Then, based on that pair, we can assign other properties, such as:
- Name
- Age
- Gender
- posture: (list of string which can be 'waving', 'holding_drink', 'sitting' etc.)
- Has_beard, has_glasses
- Length (is_tall, is_short etc)

First step is to do this merging and then put these in ED through it;s ROS service API

**Comment by LoyVanBeek** [comment]
@reinzor was working on this at https://github.com/tue-robotics/image_recognition/tree/new/people_detector

**Comment by ar13pit** [comment]
People recognition is now an independent package. Any feature additions/issues must be opened at https://github.com/tue-robotics/people_recognition/issues
