### ISSUE TITLE
Spaces in object labels

### ISSUE THREAD

**Issue by fibonatic** [tue-robotics/image_recognition#9]
Labels should not contain spaces, but underscores for compatibility in nl_robot_console.
One example now is the label "ice tea".

**Comment by reinzor** [comment]
This should be fixed in the nl_robot_console, the label can be just a string.

**Comment by LoyVanBeek** [comment]
See also https://github.com/tue-robotics/nl_robot_console/issues/5

**Comment by reinzor** [comment]
Thanks
