### ISSUE TITLE
Openpose consumes a lot of resources

### ISSUE THREAD

**Issue by ar13pit** [tue-robotics/image_recognition#92]
Openpose is known to consume a lot of resources when run continuously.

Always having an active image subscriber/publisher even though the results are needed at low frequency drains out the battery because of exhaustive GPU use.

A proposed solution is to have additional parameter in the node that starts the node in either service only mode, or both in service and topic mode.

**Comment by reinzor** [comment]
We just decided that on the `hero` robot we should remap the input topic `image` to `openpose_input_image`. Same holds for `result_image` etc. 

This way we can keep the nodes agnostic to our usage.
