### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/image_recognition#96]
CI fails on installing a new version, 1.3.1, of SciPy which requires Python 3.5. Scipy 1.2.X is still compatible with Python 2.7.

**Comment by moriarty** [comment]
@MatthijsBurgh opened an issue here: https://github.com/ros/rosdistro/issues/22075 

I added a comment with two **Dockerfiles** one reproducing the issue an one with a fix.

Just upgrade pip
```
pip install --upgrade pip
```

And you may need to clear the bash or sh hash:
https://github.com/pypa/pip/issues/5221#issuecomment-381568428
```
hash -r pip
```

**Comment by moriarty** [comment]
Actually, it looks like you can do all of this on your end, just create a Dockerfile set the **DOCKER_FILE** environment variable:

https://github.com/ros-industrial/industrial_ci/blob/legacy/doc/index.rst#use-custom-docker-images
